
# Git 구축 및 설정 {#git-setup}

처음 Git를 새로운 컴퓨터에 사용할 때, 몇가지 설정이 필요하다. 
다음에 Git을 시작할 때, 설정해야 되는 몇가지 사례가 나와있다:


*   이름과 전자우편 주소
*   선호하는 텍스트 편집기 선정
*   전역(즉, 모든 프로젝트)으로 이런 설정을 할지 여부

명령라인에서 Git 명령어는 다음과 같이 작성된다; `git verb options`, 즉, `git 동사 선택옵션`.
`verb` 가 실제로 수행하고자 하는 명령어가 되고, `options`는 `verb`에 필요할지도 모르는 추가 선택옵션 정보가 된다.
다음에 Dracula가 새로 구입한 노트북에 환경설정하는 방법이 나와있다:

```bash
$ git config --global user.name "Vlad Dracula"
$ git config --global user.email "vlad@tran.sylvan.ia"
```

Dracula 대신에 본인 이름과 본인 전자우편 주소를 사용합니다. 사용자명과 전자우편 주소는 후속 Git 활동과 연관된다.
이것이 의미하는 바는 
[GitHub](https://github.com/),
[BitBucket](https://bitbucket.org/),
[GitLab](https://gitlab.com/), 혹은 Git 호스트 서버에 푸쉬하는 어떤 변경사항도 사용자명과 전자우편 주소를 담게되는 것을 의미한다.

::: callout-tip
### 줄마침(Line Endings)

다른 키보트 타이핑과 마찬가지로, 키보드로 <kbd>Return</kbd>를 치게 되면,
컴퓨터는 엔터값을 문자로 인코딩한다.
줄마침을 표현하기 위해서 운영체제마다 별도 문자를 사용한다.
(개행 혹은 줄중단, 영어로 newline 혹은 line breaks를 들어봤을 수도 있다.)
Git이 파일을 비교하는데 이러한 문자를 사용하기 때문에,
운영체제가 다른 컴퓨텅에서 파일을 편집할 때 예기치 않은 이슈가 발생될 수 있다.
이 문제는 금번 학습 범위를 넘어서는 것이지만, [on this GitHub page](https://help.github.com/articles/dealing-with-line-endings/)
웹페이지에서 좀더 자세한 정보를 얻을 수 있다.


Git에서 줄마침을 인식하고 인코딩하는 방식을 변경하려면,
`git config`에 `core.autocrlf` 명령을 사용한다.
권장되는 설정은 다음과 같다:

맥OS와 리눅스:

```bash
$ git config --global core.autocrlf input
```

윈도우:

```bash
$ git config --global core.autocrlf true
```
:::

이번 학습에서, [GitHub](https://github.com/)을 사용하게 되는데, 사용되는 전자우편주소는 GitHub 계정을 설정할 때 사용하는 것과 같은 것이 되어야 한다.
만약, 개인정보에 대해 걱정이 된다면, [GitHub's instructions for keeping your email address private][git-privacy]을 참조한다.
GitHub에서 사적인 개인 전자우편주소를 선택하기로 했다면,
`user.email`에 동일한 전자우편주소를 사용한다. 즉, `username`을 GitHub의 설정된 것으로 바꿔놓아 `username@users.noreply.github.com`게 된다.
나중에 `git config` 명령어를 사용해서 전자우편 주소를 변경할 수 있다.

Dracula도 자신이 선호하는 텍스트 편집기를 설정해야 하는데, 다음 표를 참조한다:

| 편집기             | 환경설정 명령어                             |
|:-------------------|:-------------------------------------------------|
| Atom               | `$ git config --global core.editor "atom --wait"`|
| nano               | `$ git config --global core.editor "nano -w"`    |
| BBEdit (Mac, with command line tools) | `$ git config --global core.editor "bbedit -w"`    |
| Sublime Text (Mac) | `$ git config --global core.editor "/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl -n -w"` |
| Sublime Text (Win, 32-bit install) | `$ git config --global core.editor "'c:/program files (x86)/sublime text 3/sublime_text.exe' -w"` |
| Sublime Text (Win, 64-bit install) | `$ git config --global core.editor "'c:/program files/sublime text 3/sublime_text.exe' -w"` |
| Notepad++ (Win, 32-bit install)    | `$ git config --global core.editor "'c:/program files (x86)/Notepad++/notepad++.exe' -multiInst -notabbar -nosession -noPlugin"`|
| Notepad++ (Win, 64-bit install)    | `$ git config --global core.editor "'c:/program files/Notepad++/notepad++.exe' -multiInst -notabbar -nosession -noPlugin"`|
| Kate (Linux)       | `$ git config --global core.editor "kate"`       |
| Gedit (Linux)      | `$ git config --global core.editor "gedit --wait --new-window"`   |
| Scratch (Linux)    | `$ git config --global core.editor "scratch-text-editor"`  |
| Emacs              | `$ git config --global core.editor "emacs"`   |
| Vim                | `$ git config --global core.editor "vim"`   |
| VS Code            | $ git config --global core.editor "code --wait" |

원할 때마다 Git에 사용할 텍스트 편집기 환경설정을 다시 할 수 있다.

::: callout-tip
### Vim 나가기

다수 프로그램에서 Vim이 기본설정된 편집기다.
Vim을 예전에 사용한 적이 없고, 변경사항을 저장하지 않고 세션을 빠져나가고자 한다면,
<kbd>Esc</kbd> 다음에, `:q!`를 타이핑하고 나서 <kbd>Return</kbd>를 친다.
변경사항을 저장하고 나가려면, <kbd>Esc</kbd> 다음에, `:wq`를 타이핑하고 <kbd>Return</kbd>을 친다.

:::


앞서 실행한 상기 명령어는 한번만 실행하면 된다: `--global` 플래그는 Git으로 하여금 해당 컴퓨터에 본인 계정의
모든 프로젝트에 환경설정한 것을 사용하도록 한다.

본인이 설정한 환경설정 내용은 언제라도 다음 명령어를 입력하여 확인할 수 있다:

```bash
$ git config --list
```

원하는 만큼 환경설정을 바꿀 수도 있다: 편집기를 바꾸거나 전자우편주소를 갱신할 때 
동일한 명령어를 사용하면 된다.

::: callout-tip
### 프록시(Proxy)

일부 네트워크에서 [proxy](https://en.wikipedia.org/wiki/Proxy_server)를 사용할 필요가 있다.
이런 경우, Git에게 프록시에 대해 일러줘야 한다:

```bash
$ git config --global http.proxy proxy-url
$ git config --global https.proxy proxy-url
```

프록시를 비활성화 하는 경우, 다음 명령어를 사용한다.

```bash
$ git config --global --unset http.proxy
$ git config --global --unset https.proxy
```

:::


::: callout-tip
### Git 도움말과 매뉴얼

항상 기억할 것은 `git` 명령어를 잊은 경우, 
`-h` 선택옵션을 주어 명령어 목록을 볼 수 있고, `--help`를 사용해서 Git 매뉴얼도 이용할 수 있다:

```bash
$ git config -h
$ git config --help
```

:::

[git-privacy]: https://help.github.com/articles/keeping-your-email-address-private/


## Git 추가설정 {#git-korean}

### 로컬 PC와 SSH 키(Key) 연결 {#local-PC-ssh-keys}

[GitHub](https://github.com/)에 저장소(repository)를 만들고 여러 PC에서 작업을 진행할 경우 GitHub에 인증작업을 거쳐 진행하는 것이 여러모로 편리하다. 그중 하나의 방식이 공개키(public key)를 GitHub에 등록시켜 작업을 하는 것이 여기에 포함된다.

1. 먼저 윈도우를 사용할 경우 [Git for windows](https://gitforwindows.org/)를 다운로드 받아 설치한다. 
1. `ssh-keygen` 명령어로 공개키/비밀키를 생성한다.
1. 생성된 공개키를 [GitHub](https://github.com/) 계정에 등록시킨다.

### SSH 공개키/비밀키 생성 [^github-ssh] {#local-PC-ssh-keys-generate}

[^github-ssh]: [nickjoIT (2017), "GitHub SSH 키 생성 및 등록하여 사용하기"](https://nickjoit.tistory.com/94)

SSH 공개키/비밀키를 생성시키고 이를 GitHub 홈페이지에 등록한다. 
먼저 `ssh-keygen` 명령어에 매개변수 인자를 넣고 GitHub 전자우편주소도 함께 지정한다.


``` bash
$ ssh-keygen -t rsa -C “your_email@example.com”
```

`ssh-keygen` 명령어로 생성된 키를 GitHub에 등록한다.

- 우측상단 [Settings] &rarr; [SSH and GPG keys] &rarr; [New SSH key]

[New SSH key]를 클릭하게 되면  Title, Key를 넣는 입력부분이 보인다.
Title에 식별가능한 이름을 지정하고 앞서 생성한 `id_rsa.pub` 내용을 Key에 복사해서 붙여넣는다.

``` bash
$ cat ~/.ssh/id_rsa.pub

ssh-rsa AAAxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxYxY9 email_address@mail.com
```

### 첫 커밋(commit) {#local-PC-ssh-keys-commit}

인증작업을 완료한 후에 저장소에서 작업할 파일을 처음 커밋(commit)하는 경우 `git add`, `git commit -m`명령어를 이어서 전달시키게 되면 커밋을 때리는 사람이 누구인지를 등록하는 절차가 발생된다. `git config`를 통해 전자우편과 사용자명을 등록하게 되면 커밋을 정상적으로 진행시킬 수 있게 된다.

``` bash
$ git config --global user.email "you@example.com"
$ git config --global user.name "Your Name"
```


### 비밀번호 입력없이 푸쉬(push) [^github-without-password] {#local-PC-ssh-keys-push}

[^github-without-password]: [Stackoverflow, "How do I avoid the specification of the username and password at every git push?"](https://stackoverflow.com/questions/8588768/how-do-i-avoid-the-specification-of-the-username-and-password-at-every-git-push)

다음 단계로 비밀번호 없이 커밋된 내용을 GitHub에 전달하는 방법은 자격인증(credential) 캐싱을 통한 간단한 방법이 있다. 물론 처음에는 사용자명과 비번을 입력하는 과정을 필수적으로 거치게 된다.

``` bash
$ git config credential.helper store
$ git push https://github.com/repo.git

Username for 'https://github.com': <USERNAME>
Password for 'https://USERNAME@github.com': <PASSWORD>
```

캐쉬에 시간제한을 두어서 7200초 즉 2시간 보안을 강화시킨다.

``` bash
$ git config --global credential.helper 'cache --timeout 7200'
```


