# 서문 {.unnumbered}

코딩은 챗GPT로 대표되는 인공지능 시대에 필수적인 기술이다. 본 책 "챗GPT 코딩"은 프로그래밍의 기본 개념부터 실무에서 활용할 수 있는 다양한 도구와 기술까지 폭넓게 다룬다. 특히 챗GPT와 같은 최신 AI 기술을 자유자재로 다루기 위해 꼭 필요한 기본기를 상세히 설명한다.

책의 앞부분에서는 프로그래밍의 기초인 변수, 조건문, 반복문, 함수 등의 핵심 개념과 함께 데이터 과학, 기계 학습, 딥러닝, 나아가 생성형 AI의 기반이 되는 문자열, 파일, 리스트, 딕셔너리, 데이터프레임 등의 자료구조를 기초부터 다루고 있다.

이어서 프로그래밍과 불가분의 관계인 버전 제어에 대해 다룬다. 버전 제어를 대중화시킨 Git을 소개하고, Git의 기본 사용법부터 GitHub를 통한 원격 작업, 협업, 충돌 해결 등 실무에 필요한 기술을 자세히 안내한다. 공개 과학 기술 및 협업 과정에서 필수적으로 따라오게 되는 공개 과학, 라이선싱, 호스팅, 출처 표시, 통합 개발 환경 등도 소개하고 있다.

후반부에서는 정규표현식, 네트워크 프로그래밍, 웹서비스 활용, 작업 자동화 등 실무에서 유용한 도구와 기술을 소개하고, 마지막으로 챗GPT를 프로그래밍에 어떻게 활용할 수 있는지 설명하며, 코딩에 대한 새로운 시각을 제시한다.

본 책을 통해 프로그래밍 전반에 대한 이해를 높이고, AI 기술을 활용한 프로그래밍 작업의 생산성을 극대화할 수 있을 것이다. 지금부터 새로운 코딩 여정을 시작해보길 바란다.

## 감사의 글 {.unnumbered}

```{=html}
<style>
.flushright {
   text-align: right;
}
</style>
```

이 책이 탄생할 수 있도록 도움을 주신 여러분께 깊은 감사의 마음을 표합니다.

이 책이 출간되는데 있어 이들 모든 분들의 도움 없이는 어려웠을 것입니다. 그동안의 관심과 지원에 깊은 감사를 드리며, 이 책이 데이터 과학의 발전과 독자들에게 도움이 될 수 있기를 바라는 마음으로 마무리하겠습니다.

::: {.flushright data-latex=""}
2024년 3월 속초 청초호

이광춘
:::

